# Generated by Django 3.2.7 on 2021-09-10 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entryform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('dob', models.DateField(blank=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('whyassist', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('fathersname', models.CharField(max_length=100)),
                ('fathersoccupation', models.CharField(max_length=100)),
                ('mothersname', models.CharField(max_length=100)),
                ('mothersoccupation', models.CharField(max_length=100)),
                ('brothers', models.CharField(max_length=100)),
                ('sisters', models.CharField(max_length=100)),
                ('guardian', models.CharField(max_length=100)),
                ('guardiansoccupation', models.CharField(max_length=100)),
                ('homelocation', models.CharField(max_length=100)),
                ('hometype', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('favorites', models.CharField(max_length=200)),
                ('picture', models.ImageField(default='https://th.bing.com/th/id/R.1a169ee0e11d6f85260b7864aa916f2c?rik=F6uhG3K5RxD0Bg&pid=ImgRaw&r=0', upload_to='static/images')),
                ('datecommence', models.DateField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Entryform', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'EntryForm',
            },
        ),
    ]
