# Generated by Django 3.2.7 on 2021-09-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child_foundation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entryform',
            old_name='Gender',
            new_name='gender',
        ),
    ]
